In [13]:
import numpy as np
y = [3, 4, 5]
print(type(y))

x = np.array([2, 4, 6, 8, 10])
print(x)
print(x[3])

<class 'list'>
[ 2  4  6  8 10]
8


In [3]:
#see what happens when you try to "add" lists
#try to divide as well and see what you get
x1 = [1,2,3,4,5]
print(type(x1))
x2 = [1,2,3,4,5]
print(x1 + x2)

<class 'list'>
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [4]:
# now define two numpy arrays - arange will automativally create 
# values from 0 to 19 for each array
# voila, all math operations in arrays work great! try division as well
y1 = np.arange(20)
y2 = np.arange(20)
print(y1)
print(y1+y2)
print(y1*y2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361]


In [5]:
# if you have a numpy array you can even derive conditional arrays 

print(y1 > 15)
print( y1[y1 > 15] )

[False False False False False False False False False False False False
 False False False False  True  True  True  True]
[16 17 18 19]


In [6]:
# you can examine the number of dimensions and data types of numpy arrays

print(y1.ndim) # one dimension
print(y1.dtype) # integer array 64 bits


1
int64


In [7]:
# two-dimensional arrays
y3 = np.array([[1,2],[4,5]])
print(y3)
# query size, shape of arrays and quick operations
print(y3.size, y3.shape, y3.sum())

[[1 2]
 [4 5]]
4 (2, 2) 12


In [21]:
x = y3.shape


In [22]:
#pandas uses numpy to represent enter data frames, like a spreadsheet, or a dataset

import pandas as pd

iris_csv = pd.read_csv("iris.csv")

print(type(iris_csv))

<class 'pandas.core.frame.DataFrame'>


In [24]:
# head and describe return top few rows and summary stats
print(iris_csv.head(10))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa


Great (but long) overview of different ways you can select rows and columns in pandas

https://medium.com/dunder-data/selecting-subsets-of-data-in-pandas-6fcd0170be9c

Also go through basic pandas data frame tutorial below

https://github.com/adeshpande3/Pandas-Tutorial/blob/master/Pandas%20Tutorial.ipynb

In [28]:
#use dot columns method on the data frame to get the column names
#use brackets notation to pull out a column
x = iris_csv.columns
print(type(x),x[0])
print(type(iris_csv['sepal_length']))

<class 'pandas.core.indexes.base.Index'> sepal_length
<class 'pandas.core.series.Series'>


In [17]:
x = iris_csv.columns

In [15]:
print(x, type(x))

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object') <class 'pandas.core.indexes.base.Index'>


In [21]:
for i in x:
    print(type(iris_csv[i]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


In [ ]:
# to retrive a row of data use index location (iloc) function with row number
print(iris_csv.iloc[0])
#accessing a row and column
print(iris_csv['sepal_length'].iloc[0])

In [ ]:
#to access a subset of rows and columns, first create names of colums
cols = iris_csv[['sepal_length', 'sepal_width']]
print(cols.iloc[5:20])

