In [1]:
#Question2 :
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn

In [2]:
# importing the mnist data set 
try:
    from sklearn.datasets import fetch_openml
    mnist = fetch_openml('mnist_784', version=1, cache=True)
    mnist.target = mnist.target.astype(np.int8) # fetch_openml() returns targets as strings
    #sort_by_target(mnist) # fetch_openml() returns an unsorted dataset
except ImportError:
    from sklearn.datasets import fetch_mldata
    mnist = fetch_mldata('MNIST original')

In [3]:
print(type(mnist))

<class 'sklearn.utils.Bunch'>


In [8]:
X, y = mnist["data"], mnist["target"]

In [9]:
# checking the type of x and y and they should be numpy
type(X), type(y)
#X = X1.to_numpy()
#y = y1.to_numpy()
#type(X), type(y)

(numpy.ndarray, numpy.ndarray)

In [10]:
X.shape, y.shape

((70000, 784), (70000,))

In [11]:
#selecting data from the 70000 data of mnist
X_train, X_test, y_train, y_test = X[:60000], X[60000:],y[:60000], y[60000:]

In [12]:
shuffle_index=np.random.permutation(60000)
type(X_train), type(y_train)

(numpy.ndarray, numpy.ndarray)

In [16]:
#Creating train dataset for 1k random data
X_train, y_train = X_train[shuffle_index], y_train[shuffle_index]
X_train_sample1,y_train_sample1 = X_train[:1000],y_train[:1000]

In [17]:
#Creating train dataset for 5k random data
X_train, y_train = X_train[shuffle_index], y_train[shuffle_index]
X_train_sample2,y_train_sample2 = X_train[:5000],y_train[:5000]

In [18]:
# test dataset with random 2k
shuffle_index2 = np.random.permutation(10000)
X_test,y_test = X_test[shuffle_index2],y_test[shuffle_index2]
X_test_sample,y_test_sample = X_test[:2000],y_test[:2000]

In [36]:
# y train and test for 1k train data set
print(y_train_sample[:30])
y_train_2_1 = (y_train_sample1 == 2) 
y_test_2_1 = (y_test_sample == 2) 

[9 9 9 1 6 5 3 2 1 2 5 6 5 6 8 6 2 0 4 6 5 9 4 8 4 9 2 2 3 4]


In [37]:
# train and test for 5k training data set
print(y_train_sample[:30])
y_train_2_5 = (y_train_sample2 == 2) 
y_test_2_5 = (y_test_sample == 2) 

[9 9 9 1 6 5 3 2 1 2 5 6 5 6 8 6 2 0 4 6 5 9 4 8 4 9 2 2 3 4]


In [38]:
# SGD for traing data with 1 k
from sklearn.linear_model import SGDClassifier
sgd_1 = SGDClassifier(random_state=42)
sgd_1 = sgd_1.fit(X_train_sample1,y_train_2_1)
sgd_1.predict(X_test_sample[:15])

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False])

In [39]:
# SGD for traing data with 5k
from sklearn.linear_model import SGDClassifier
sgd_5 = SGDClassifier(random_state=50)
sgd_5 = sgd_5.fit(X_train_sample2,y_train_2_5)
sgd_5.predict(X_test_sample[:15])

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False])

In [40]:
from sklearn.model_selection import cross_val_predict
y_test_1_pred = cross_val_predict(sgd_1, X_test_sample, y_test_2_1, cv=3)

In [41]:
# confusion matrix for 5 data set
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test_2_1, y_test_1_pred) # actual vs predicted

array([[1763,   34],
       [  43,  160]])

In [42]:
#from sklearn.model_selection import cross_val_predict
#y_test_5_pred = cross_val_predict(sgd_5, X_test_sample, y_test_2_5, cv=3)

In [43]:
# confusion matrix for 5 training data set
y_test_5_pred = cross_val_predict(sgd_5, X_test_sample, y_test_2_5, cv=3)
confusion_matrix(y_test_2_5, y_test_5_pred) # actual vs predicted

array([[1763,   34],
       [  36,  167]])

# Inference : From the above both confusion matrix of the 1k train data and 5k train data we can see that the confusion matrix for the training data set with 5k has more true positives than the confusion matrix with 1k train data set. As both the data sets are to predict for 2 image. The true positive rate for the second model is good. But just by the confusion matrix we can predict the accuracy of the model as the possibilty can be that the 5k data might have more images with 2. 